---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: mw
  namespace: logging
spec:
  version: 7.6.1
  count: 1
  elasticsearchRef:
    name: mw
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 256Mi
            cpu: 0.2
          limits:
            memory: 512Mi
            cpu: 0.5
