---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kibana-tls
  namespace: logging
spec:
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - kibana.alexos.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: kibana-tls
  commonName: kibana.alexos.dev
  dnsNames:
  - kibana.alexos.dev
