---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch
  namespace: logging
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
