---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs
data:
  kubernetes.yml: |-
    - type: container
      paths:
      - '/var/lib/docker/containers/*/*.log'
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
      - rename:
          when.has_fields: ['log']
          fields:
          - from: 'log'
            to: 'filebeat.log'
      - decode_json_fields:
          when.regexp.message: '^{'
          fields: ["message"]
          target: "log"
          overwrite_keys: true
      - drop_event:
          when:
            or:
            - contains:
                kubernetes.container.name: "logstash"
      - timestamp:
          field: log.timestamp
          layouts:
          - '2006-01-02 15:04:05.000'
          test:
          - '2019-10-25 06:57:05.259'
