# filebeat.config:
#   inputs:
  #   # Mounted `filebeat-inputs` configmap:
  #   path: ${path.config}/inputs.d/*.yml

  #   # Reload inputs configs as they change:
  #   reload.enabled: true

  #   # Try to consolidate multiline messages that have indented following lines - i.e. some stack traces.
  #   multiline.pattern: '^[[:space:]]'
  #   multiline.negate: false
  #   multiline.match: after

  # modules:
  #   path: ${path.config}/modules.d/*.yml
  #   # Reload module configs as they change:
  #   reload.enabled: true

filebeat.autodiscover:
  providers:
    - type: kubernetes
      host: ${NODE_NAME}
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/log/containers/*${data.kubernetes.container.id}.log

setup.dashboards.enabled: false

processors:
- add_cloud_metadata:
- add_host_metadata:

# http:
#   enabled: true
#   host: localhost
#   port: 5066

# logging:
#   json: true
#   metrics.enabled: false

output.elasticsearch:
  hosts: ['https://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
  ssl.certificate_authorities:
  - /mnt/elastic/tls.crt
