---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

commonLabels:
  component: filebeat

resources:
- daemonset.yaml
- podmonitor.yaml
- psp.yaml
- rbac.yaml
# this one doesn't need a hash suffix as filebeat will reload the inputs config in place
- filebeat-inputs.configmap.yaml

# we want this one to have a hash suffix to force redeployment on change
configMapGenerator:
- name: filebeat-config
  files:
  - filebeat.yml

configurations:
- kustomizeconfig.yaml
